#pragma once
#include <windows.h>
#include <stdint.h>

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

#define PILKA_PROMIEN 7
#define WYSOKOSC_PASKA_NAGLOWKA_OKNA 20
#define PILKA_DOMYSLNA_WARTOSC_PREDKOSCI 5
#define PILKA_POLOZENIE_STARTOWE_X (WINDOW_WIDTH / 2)
#define PILKA_POLOZENIE_STARTOWE_Y ((WINDOW_HEIGHT / 2) - WYSOKOSC_PASKA_NAGLOWKA_OKNA)

#define DOMYSLNA_POZYCJA_SLUPKA_GRACZ1_X 10
#define DOMYSLNA_POZYCJA_SLUPKA_GRACZ1_Y (WINDOW_HEIGHT / 2) - WYSOKOSC_PASKA_NAGLOWKA_OKNA
#define DOMYSLNA_POZYCJA_SLUPKA_GRACZ2_X WINDOW_WIDTH - 25
#define DOMYSLNA_POZYCJA_SLUPKA_GRACZ2_Y (WINDOW_HEIGHT / 2) - WYSOKOSC_PASKA_NAGLOWKA_OKNA

#define PREDKOSC_PRZESUWANIA_PADOW 5

HPEN whitePen;
HBRUSH blackBrush;
uint32_t pilkaX = PILKA_POLOZENIE_STARTOWE_X;
uint32_t pilkaY = PILKA_POLOZENIE_STARTOWE_Y;

int32_t pilkaPredkoscX = 0;
int32_t pilkaPredkoscY = 0;
int32_t pilkaWartoscPredkosci = PILKA_DOMYSLNA_WARTOSC_PREDKOSCI;

uint32_t gracz1wynik = 0;
uint32_t gracz2wynik = 0;

uint32_t slupek_gracz1_x = DOMYSLNA_POZYCJA_SLUPKA_GRACZ1_X;
uint32_t slupek_gracz1_y = DOMYSLNA_POZYCJA_SLUPKA_GRACZ1_Y;
uint32_t slupek_gracz2_x = DOMYSLNA_POZYCJA_SLUPKA_GRACZ2_X;
uint32_t slupek_gracz2_y = DOMYSLNA_POZYCJA_SLUPKA_GRACZ2_Y;



LRESULT CALLBACK WindowProc(HWND windowHandle, UINT message, WPARAM wparam, LPARAM lparam);
void przesun_pilke();
